/**
 * LUXORA demo catalogue.
 *
 * Everything here is hand-authored, realistic content — prices are INR per night and
 * deliberately span budget-boutique to ultra-luxury so filters have something to chew on.
 * Images reference the curated local manifest (see `scripts/media`) which mirrors how a
 * Cloudinary `public_id` would be used in production.
 */

const A = (keys) => keys.map((key) => ({ key }));

/**
 * slug, name, city, country, neighbourhood, type, stars, featured, tags,
 * cover slot, gallery slots, amenities, price hint
 */
export const HOTELS = [
  {
    slug: 'rambagh-court',
    name: 'Rambagh Court',
    city: 'Jaipur',
    country: 'India',
    region: 'Rajasthan',
    neighbourhood: 'Civil Lines',
    lat: 26.9083,
    lng: 75.8039,
    timezone: 'Asia/Kolkata',
    propertyType: 'ryad',
    starRating: 6,
    featured: true,
    priceFrom: 24500,
    tagline: 'A restored maharaja residence where courtyards hold the cool until noon.',
    description: [
      'Rambagh Court is a 1928 royal guesthouse brought back to life over four years by a Jaipur conservation architect. Twenty-two rooms open onto three lime-plaster courtyards, each with its own step-well and a neem tree older than the building.',
      'The kitchen serves Rajasthani cooking with a light hand — laal maas at lunch, thali finished on the roof at dusk — and the spa buries itself two floors down, where the old wine cellars became treatment rooms.',
      'Arrive by car from the airport in forty minutes; leave for Amber Fort before eight and you will have the ramparts to yourself.',
    ],
    amenities: A(['wifi', 'pool', 'spa', 'restaurant', 'gym', 'parking', 'airportTransfer', 'butler', 'breakfast', 'concierge', 'laundry', 'roomService', 'aircon', 'business']),
    highlights: [
      { title: 'Three private courtyards', body: 'Lime-plaster verandahs that stay 6°C cooler than the street.', icon: 'Sun' },
      { title: 'Cellar spa', body: 'Six treatment rooms carved from the 1920s vaults, open until midnight.', icon: 'Flower2' },
      { title: 'Fort at first light', body: 'Complimentary 6:30am Amber Fort drives, booked with the concierge.', icon: 'Landmark' },
    ],
    policies: {
      checkIn: '14:00',
      checkOut: '11:30',
      cancellation: 'Free cancellation until 16:00 local time, 5 days before arrival.',
      pets: 'Small dogs welcome in garden rooms (₹1,500 per stay).',
      notes: [
        'The rooftop restaurant closes for service between 16:00 and 18:30.',
        'Heritage listing means lifts are unavailable in the east wing.',
      ],
    },
    gallery: ['cov-rambagh', 'am-suite', 'am-pool', 'am-desk', 'room-living', 'am-spa'],
    rooms: [
      {
        name: 'Courtyard Deluxe',
        roomType: 'deluxe',
        price: 24500,
        maxGuests: 2,
        size: 520,
        beds: '1 king bed',
        view: 'Courtyard',
        inventory: 6,
        description: 'Lime-plaster walls, a carved jharokha window and a four-poster that faces the neem tree.',
        amenities: ['wifi', 'aircon', 'roomService', 'minibar', 'bathtub'],
        images: ['am-suite', 'room-living', 'am-desk'],
      },
      {
        name: 'Stepwell Suite',
        roomType: 'suite',
        price: 38900,
        maxGuests: 3,
        size: 890,
        beds: '1 king + daybed',
        view: 'Stepwell & garden',
        inventory: 4,
        featured: true,
        description: 'A sitting room with the original 1928 tiles, plus a private stair down to the baori.',
        amenities: ['wifi', 'aircon', 'butler', 'roomService', 'bathtub', 'business'],
        images: ['room-living', 'am-suite', 'am-pool'],
      },
      {
        name: 'Maharani Villa',
        roomType: 'villa',
        price: 74000,
        maxGuests: 4,
        size: 1650,
        beds: '2 kings',
        view: 'Private garden',
        inventory: 2,
        description: 'Two bedrooms around a walled garden, with a cook on call and its own 12-metre pool.',
        amenities: ['wifi', 'poolVilla', 'butler', 'kitchen', 'aircon', 'laundry'],
        images: ['am-pool', 'am-suite', 'room-living', 'am-desk'],
      },
    ],
    reviews: [
      { rating: 5, title: 'Better than the palace hotels', body: 'We cancelled a much more famous address two streets away because this one was half the price and twice the character. The courtyard breakfasts were unhurried and the staff never once made us feel rushed out of a chair.', name: 'Ishaan M.', travelType: 'couple' },
      { rating: 5, title: 'The cellar spa is worth the fare', body: 'Ninety minutes of abhyanga at 11pm after a day in the old city. Water in the plunge pool was genuinely cold, which in May is a miracle.', name: 'Charlotte D.', travelType: 'solo' },
      { rating: 4, title: 'Exceptional, with a caveat', body: 'Rooms are beautiful and the heritage building means you will be climbing stairs. East wing guests should ask for a ground-floor room if knees are a concern. Rooftop at sunset is the best hour in Jaipur.', name: 'Marcus W.', travelType: 'family' },
    ],
  },

  {
    slug: 'amber-sky-haveli',
    name: 'Amber Sky Haveli',
    city: 'Jaipur',
    country: 'India',
    region: 'Rajasthan',
    neighbourhood: 'Galtore',
    lat: 26.9384,
    lng: 75.8527,
    timezone: 'Asia/Kolkata',
    propertyType: 'boutique',
    starRating: 4,
    featured: false,
    priceFrom: 8900,
    tagline: 'Nine rooms, one rooftop, and the Aravalli ridge close enough to touch.',
    description: [
      'A merchant haveli on the old Amber road, converted into nine rooms with a shared roof garden that earns the name. Owners Neelam and Vikram cook if the kitchen is short-staffed, which is why the eggs are late on Sundays and worth it.',
      'It is 12km from the city centre and 35 from the fort, so plan around that: cheap and cheerful with a view, not a base for nightlife.',
    ],
    amenities: A(['wifi', 'restaurant', 'parking', 'breakfast', 'laundry', 'aircon']),
    highlights: [
      { title: 'Rooftop at dawn', body: 'Kettle on at 5:30am; the ridge fills with light before breakfast is served.', icon: 'Sunrise' },
      { title: 'Owner-run', body: 'Nine rooms means the people who built the place are the people who run it.', icon: 'HeartHandshake' },
    ],
    policies: {
      checkIn: '12:00',
      checkOut: '10:00',
      cancellation: 'Free cancellation until 24 hours before arrival.',
      pets: 'Not permitted.',
      notes: ['Airport transfers are shared with other guests where possible (₹900 per seat).'],
    },
    gallery: ['cov-ambersky', 'room-king', 'am-dining', 'room-living', 'am-beach'],
    rooms: [
      {
        name: 'Garden Room',
        roomType: 'garden',
        price: 8900,
        maxGuests: 2,
        size: 280,
        beds: '1 queen bed',
        view: 'Neighbourhood',
        inventory: 3,
        description: 'Ground floor, opens straight onto the Bougainvillaea and the breakfast tables.',
        amenities: ['wifi', 'aircon', 'breakfast'],
        images: ['room-king', 'am-dining'],
      },
      {
        name: 'Ridge View Room',
        roomType: 'deluxe',
        price: 12400,
        maxGuests: 3,
        size: 360,
        beds: '1 king + rollaway',
        view: 'Aravalli ridge',
        inventory: 4,
        featured: true,
        description: 'First floor, deep window seat, the only room where you can watch the light move across the hills from the bed.',
        amenities: ['wifi', 'aircon', 'breakfast', 'roomService'],
        images: ['am-suite', 'room-living'],
      },
    ],
    reviews: [
      { rating: 5, title: 'The rooftop sold me', body: 'Simple rooms, extraordinary sunrises, and Neelam\'s chai at 6am. We extended by two nights.', name: 'Farah K.', travelType: 'solo' },
      { rating: 4, title: 'Go for the view, not the location', body: 'You will need a car for everything. Once you accept that, it is one of the loveliest quiet stays we have had in Rajasthan.', name: 'Tom & Elena', travelType: 'couple' },
    ],
  },

  {
    slug: 'the-palm-resort-atlantis',
    name: 'The Palm Resort',
    city: 'Dubai',
    country: 'United Arab Emirates',
    region: 'Dubai',
    neighbourhood: 'Palm Jumeirah',
    lat: 25.1124,
    lng: 55.139,
    timezone: 'Asia/Dubai',
    propertyType: 'resort',
    starRating: 6,
    featured: true,
    priceFrom: 18500,
    tagline: 'A crescent of private terraces facing the skyline the postcards use.',
    description: [
      'The Palm Resort occupies 340 metres of crescent beach on Palm Jumeirah, with 188 rooms arranged so that every balcony looks at the water rather than at a neighbour.',
      'There are eleven food and beverage outlets, of which three matter: the raw bar at the pool, a live-fire Levantine kitchen called Zar, and a rooftop that is open only for dinner and only for guests.',
      'The house pool runs 62 metres and is heated to 29°C from October to April. Families take the west towers; couples ask for the dune-side rooms, which are quieter and cost about 15% less.',
    ],
    amenities: A(['wifi', 'pool', 'spa', 'restaurant', 'gym', 'parking', 'airportTransfer', 'breakfast', 'beachAccess', 'concierge', 'roomService', 'kidsClub', 'yacht', 'business', 'evCharging', 'aircon']),
    highlights: [
      { title: '62m house pool', body: 'Heated from October, with a swim-up bar and lifeguards until 21:00.', icon: 'Waves' },
      { title: 'Skyline balconies', body: 'Every room faces the water; 78% have uninterrupted Burj Khalifa sightlines.', icon: 'Building2' },
      { title: 'Marina berth', body: 'Guests can book a day boat from the resort\'s own jetty.', icon: 'Ship' },
    ],
    policies: {
      checkIn: '15:00',
      checkOut: '12:00',
      cancellation: 'Free cancellation until 18:00 local time, 3 days before arrival.',
      pets: 'Not permitted, except service animals.',
      notes: [
        'Tourism dirham (AED 20 per room per night) is collected on arrival and is not included in the total shown.',
        'Zar requires 24 hours\' notice and is closed Tuesdays.',
      ],
    },
    gallery: ['cov-atlantis', 'am-infinity', 'am-suite', 'am-bar', 'am-spa', 'am-poolside', 'room-terrace'],
    rooms: [
      {
        name: 'Horizon Room',
        roomType: 'deluxe',
        price: 18500,
        maxGuests: 3,
        size: 560,
        beds: '1 king bed',
        view: 'Palm & sea',
        inventory: 42,
        description: 'The entry room, and the one repeat guests still ask for: a 4-metre balcony, blackout that works, and a bath with a window.',
        amenities: ['wifi', 'aircon', 'roomService', 'minibar', 'poolAccess'],
        images: ['am-suite', 'am-infinity', 'room-terrace'],
        featured: true,
      },
      {
        name: 'Dune Suite',
        roomType: 'suite',
        price: 27900,
        maxGuests: 4,
        size: 940,
        beds: '1 king + sofa bed',
        view: 'Garden & skyline',
        inventory: 18,
        description: 'Separate lounge, powder room, and a terrace wide enough to eat on. Pool shuttle stops at your door.',
        amenities: ['wifi', 'aircon', 'butler', 'roomService', 'business', 'bathtub'],
        images: ['room-living', 'am-bar', 'am-suite'],
      },
      {
        name: 'Beachfront Villa',
        roomType: 'villa',
        price: 96000,
        maxGuests: 6,
        size: 2400,
        beds: '3 kings',
        view: 'Direct beach',
        inventory: 6,
        description: 'Three bedrooms, private 14-metre pool, beach steps, and a butler who is genuinely never in the way.',
        amenities: ['wifi', 'poolVilla', 'beachAccess', 'butler', 'kitchen', 'laundry', 'aircon'],
        images: ['am-infinity', 'am-poolside', 'am-suite', 'room-villa'],
      },
    ],
    reviews: [
      { rating: 5, title: 'The balcony is the whole holiday', body: 'We paid for the room category with the skyline and used it every single evening. Service at the pool raw bar was fast without being hover-y.', name: 'Aditya R.', travelType: 'family' },
      { rating: 4, title: 'Good, but book Zar early', body: 'Resort is immaculate. Zar was the best meal of the trip and had a 48-hour wait when we tried to book late. Also mind the tourism dirham at checkout.', name: 'Lena V.', travelType: 'couple' },
      { rating: 5, title: 'Dune Suite is the smart buy', body: 'Saved about AED 700 a night versus the villa, still had a terrace big enough for dinner, and the pool shuttle meant we never touched a car.', name: 'Daniel O.', travelType: 'friends' },
    ],
  },

  {
    slug: 'marina-bay-suites',
    name: 'Marina Bay Suites',
    city: 'Dubai',
    country: 'United Arab Emirates',
    region: 'Dubai',
    neighbourhood: 'Dubai Marina',
    lat: 25.0805,
    lng: 55.1403,
    timezone: 'Asia/Dubai',
    propertyType: 'hotel',
    starRating: 5,
    featured: false,
    priceFrom: 11200,
    tagline: 'Serviced apartments for people who would rather cook than queue for breakfast.',
    description: [
      'Ninety-six long-stay suites in a glass tower on the marina walk, run like a small hotel rather than an apartment block: daily housekeeping, a gym open 24 hours, and a reception that will absolutely take a delivery for you.',
      'Kitchens are the point. Induction hobs, real knives, a dishwasher that fits a week of plates. The metro is a four-minute walk and JBR beach is eleven.',
    ],
    amenities: A(['wifi', 'gym', 'parking', 'business', 'laundry', 'aircon', 'evCharging', 'concierge', 'pool']),
    highlights: [
      { title: 'Full kitchens', body: 'Including knives, pans and a coffee grinder — most "aparthotels" skip these.', icon: 'ChefHat' },
      { title: 'Walk to everything', body: 'Metro, beach and Marina Mall all under 12 minutes on foot.', icon: 'TrainFront' },
    ],
    policies: {
      checkIn: '15:00',
      checkOut: '11:00',
      cancellation: 'Free cancellation until 48 hours before arrival.',
      pets: 'Pets allowed on request (AED 100 per night).',
      notes: ['Building has no on-site restaurant; breakfast is delivered from the bakery downstairs from 06:30.'],
    },
    gallery: ['cov-marina', 'room-living', 'am-gym', 'room-king', 'am-desk'],
    rooms: [
      {
        name: 'Marina Studio',
        roomType: 'deluxe',
        price: 11200,
        maxGuests: 2,
        size: 480,
        beds: '1 king bed',
        view: 'Marina',
        inventory: 22,
        description: 'Kitchenette, marble-clad bath, and a window seat facing the moored boats.',
        amenities: ['wifi', 'aircon', 'kitchen', 'gymAccess', 'laundry'],
        images: ['room-king', 'room-living'],
      },
      {
        name: 'One-Bedroom Skyline',
        roomType: 'suite',
        price: 18600,
        maxGuests: 4,
        size: 900,
        beds: '1 king + sofa bed',
        view: 'Skyline & sea',
        inventory: 14,
        featured: true,
        description: 'Real walls between bedroom and living room, a dining table for six, and floors 34 and up.',
        amenities: ['wifi', 'aircon', 'kitchen', 'business', 'gymAccess', 'washer'],
        images: ['room-living', 'am-suite', 'am-gym'],
      },
    ],
    reviews: [
      { rating: 5, title: 'Perfect for a two-week stay', body: 'We came for a work trip and stayed a fortnight. Gym at 5am, dishwasher that works, and the metro link is genuinely as advertised.', name: 'Sara B.', travelType: 'business' },
      { rating: 4, title: 'No restaurant is the trade-off', body: 'Beautiful suites and great value for Marina, but bring a coat for the walk to the bakery if you eat early in winter.', name: 'Kwame A.', travelType: 'solo' },
    ],
  },

  {
    slug: 'desert-oasis-camp',
    name: 'Desert Oasis Camp',
    city: 'Dubai',
    country: 'United Arab Emirates',
    region: 'Dubai',
    neighbourhood: 'Al Marmoom Conservation Reserve',
    lat: 25.022,
    lng: 55.3872,
    timezone: 'Asia/Dubai',
    propertyType: 'glamp',
    starRating: 5,
    featured: true,
    priceFrom: 21400,
    tagline: 'Twelve tents in a protected dune field, and no light pollution for 40km.',
    description: [
      'A small, deliberate camp in the Al Marmoom reserve: twelve tents, a shared majlis, dinner cooked on coals, and a guide who knows where the oryx bed down. Solar power only — the lighting is warm and low on purpose.',
      'Transfer from Dubai is 55 minutes. You will be outside the city\'s network coverage, which staff usefully describe as "the point".',
    ],
    amenities: A(['restaurant', 'wifi', 'airportTransfer', 'butler', 'concierge', 'spa']),
    highlights: [
      { title: 'Dark-sky reserve', body: 'Guided stargazing nightly; the Milky Way is genuinely visible here.', icon: 'Sparkles' },
      { title: 'Dune drives included', body: 'Two per stay, dawn or dusk, in a 4x4 with a Bedouin driver.', icon: 'Compass' },
    ],
    policies: {
      checkIn: '15:30',
      checkOut: '11:00',
      cancellation: 'Free cancellation until 72 hours before arrival; weather cancellations are refunded in full.',
      pets: 'Not permitted — this is a wildlife reserve.',
      notes: [
        'Tents have en-suite bathrooms and hot water, but no air conditioning — fans and thick canvas do the work.',
        'Single-use plastic is banned on site.',
      ],
    },
    gallery: ['cov-desert', 'am-bar', 'room-living', 'am-dining'],
    rooms: [
      {
        name: 'Dune Tent',
        roomType: 'deluxe',
        price: 21400,
        maxGuests: 2,
        size: 620,
        beds: '1 king bed',
        view: 'Open dune field',
        inventory: 8,
        description: 'Hand-woven carpets, a private deck facing west, and an en-suite with a copper tub.',
        amenities: ['wifi', 'bathtub', 'diningPlan'],
        images: ['am-bar', 'room-living'],
        featured: true,
      },
      {
        name: 'Family Majlis Tent',
        roomType: 'suite',
        price: 34900,
        maxGuests: 5,
        size: 1150,
        beds: '1 king + 2 twins',
        view: 'Dune & camp fire',
        inventory: 4,
        description: 'Two connected tents with their own majlis, so children can stay up by the fire without adults surrendering the evening.',
        amenities: ['wifi', 'bathtub', 'diningPlan', 'kids'],
        images: ['room-living', 'am-dining'],
      },
    ],
    reviews: [
      { rating: 5, title: 'Silence you can hear', body: 'The stargazing was the memory of our trip, not the room — which says a lot, because the tent was gorgeous too. Take the dawn drive.', name: 'Nadia F.', travelType: 'couple' },
      { rating: 5, title: 'Not luxury as usual, and better', body: 'No AC and no TV, fans and a fire instead. Dinner on coals at 8pm, and it was the best meal we had in the UAE.', name: 'Peter H.', travelType: 'friends' },
    ],
  },

  {
    slug: 'uluwatu-cliff-house',
    name: 'Uluwatu Cliff House',
    city: 'Bali',
    country: 'Indonesia',
    region: 'Bali',
    neighbourhood: 'Uluwatu',
    lat: -8.8291,
    lng: 115.0849,
    timezone: 'Asia/Makassar',
    propertyType: 'villa',
    starRating: 6,
    featured: true,
    priceFrom: 31200,
    tagline: 'Eighteen villas on the limestone shelf, with the swell as background noise.',
    description: [
      'Built down the cliff face rather than on top of it, so each villa gets its own horizontal slice of the Indian Ocean. Concrete, teak and volcanic stone, with no handrails by design and a resident engineer who maintains the paths.',
      'The house reef is a 20-minute walk south at low tide. Surfers take the shuttle break at 6am; everyone else sleeps in and eats a long breakfast.',
      'One villa was destroyed by a rockfall in 2024 and rebuilt to a revised setback — the resort now keeps a geologist on retainer, which is exactly the kind of thing you want to read before booking a cliff.',
    ],
    amenities: A(['wifi', 'pool', 'poolVilla', 'spa', 'restaurant', 'gym', 'beachAccess', 'butler', 'breakfast', 'yacht', 'airportTransfer', 'roomService', 'petFriendly']),
    highlights: [
      { title: 'Ocean from the bed', body: 'Every villa faces due west; sunset is 18:20 in July, 18:50 in January.', icon: 'Sunset' },
      { title: 'Cliff elevator', body: 'A cage lift runs to a private swim platform at low tide.', icon: 'ArrowDownToLine' },
      { title: 'Reef & surf', body: 'House reef 1.2km south, Padang Padang 9 minutes by car.', icon: 'Waves' },
    ],
    policies: {
      checkIn: '15:00',
      checkOut: '12:00',
      cancellation: 'Free cancellation until 10 days before arrival.',
      pets: 'Dogs and cats welcome, up to two per villa.',
      notes: [
        'Villa 7 and 8 are reached by 42 steps; staff will move guests on request.',
        'Monsoon season (Dec–Feb) brings strong swell and occasional path closures.',
      ],
    },
    gallery: ['cov-uluwatu', 'room-villa', 'am-infinity', 'am-spa', 'am-dining', 'room-terrace'],
    rooms: [
      {
        name: 'Cliff Villa',
        roomType: 'villa',
        price: 31200,
        maxGuests: 2,
        size: 1100,
        beds: '1 king bed',
        view: 'Ocean',
        inventory: 8,
        featured: true,
        description: 'One bedroom, 9-metre plunge pool, an outdoor bath cut into the limestone, and nobody within sight.',
        amenities: ['wifi', 'poolVilla', 'aircon', 'butler', 'bathtub'],
        images: ['room-villa', 'am-infinity', 'am-spa'],
      },
      {
        name: 'Two-Bedroom Reef Villa',
        roomType: 'villa',
        price: 52400,
        maxGuests: 5,
        size: 2100,
        beds: '2 kings + daybed',
        view: 'Ocean & reef path',
        inventory: 6,
        description: 'A shared pavilion with a kitchen and a private chef on call, plus the shorter walk down to the reef.',
        amenities: ['wifi', 'poolVilla', 'kitchen', 'butler', 'kids', 'laundry', 'aircon'],
        images: ['am-poolside', 'room-villa', 'am-dining'],
      },
      {
        name: 'Owner\'s House',
        roomType: 'penthouse',
        price: 88000,
        maxGuests: 8,
        size: 4200,
        beds: '4 kings',
        view: 'Panoramic coast',
        inventory: 1,
        description: 'Four bedrooms on two levels, a 20-metre lap pool, and a sala where dinner is served under a roof of alang-alang.',
        amenities: ['wifi', 'poolVilla', 'kitchen', 'butler', 'chef', 'gymAccess', 'laundry', 'aircon'],
        images: ['am-infinity', 'am-spa', 'room-living', 'am-dining'],
      },
    ],
    reviews: [
      { rating: 5, title: 'Worth the transfer from Seminyak', body: 'Ninety minutes on the road, then nothing but ocean and a staff member who remembered our coffee order from day one. The plunge pool was used hourly.', name: 'Mikael & Aina', travelType: 'couple' },
      { rating: 5, title: 'The geologist note made me book', body: 'I read about the rebuild before coming and it told me everything about how this place is run. Steps to Villa 7 are real — we asked for a swap and they did it free.', name: 'Ruth P.', travelType: 'solo' },
      { rating: 4, title: 'Book the low tide', body: 'The reef walk is only good at low tide; the concierge gives you the daily window and it is worth planning the whole day around it.', name: 'Aakash S.', travelType: 'family' },
    ],
  },

  {
    slug: 'ubud-jungle-retreat',
    name: 'Ubud Jungle Retreat',
    city: 'Bali',
    country: 'Indonesia',
    region: 'Bali',
    neighbourhood: 'Sayan Ridge',
    lat: -8.4723,
    lng: 115.2552,
    timezone: 'Asia/Makassar',
    propertyType: 'resort',
    starRating: 5,
    featured: false,
    priceFrom: 12800,
    tagline: 'Rainforest on three sides, the Petanu river below, no road noise at all.',
    description: [
      'Thirty-one rooms and suites stepping down a gorge on the Sayan ridge, joined by a footbridge that has become the most photographed piece of timber in Bali. Breakfast is delivered to your sala by basket.',
      'The spa building hangs over the river on cantilevered beams. Yoga runs at 6:45 and is included. Rice terraces are a 12-minute drive; the town centre is a 25-minute one, in traffic.',
    ],
    amenities: A(['wifi', 'pool', 'spa', 'restaurant', 'gym', 'breakfast', 'airportTransfer', 'concierge', 'laundry', 'petFriendly', 'aircon']),
    highlights: [
      { title: 'Gorge footbridge', body: 'Connecting the two wings, 40 metres above the river bed.', icon: 'Waypoints' },
      { title: 'Included sunrise yoga', body: 'Daily 6:45 in an open-sided bale; mats provided.', icon: 'Flower2' },
    ],
    policies: {
      checkIn: '14:00',
      checkOut: '12:00',
      cancellation: 'Free cancellation until 7 days before arrival.',
      pets: 'Not permitted (monkeys are the local pest).',
      notes: ['Geckos and evening frogs are part of the deal — this is a rainforest.'],
    },
    gallery: ['cov-ubud', 'am-pool', 'am-spa', 'room-living', 'am-dining'],
    rooms: [
      {
        name: 'Garden Room',
        roomType: 'garden',
        price: 12800,
        maxGuests: 2,
        size: 420,
        beds: '1 king bed',
        view: 'Garden',
        inventory: 9,
        description: 'Lower level, open-air bathroom with a stone tub, and the sound of the river without the drop.',
        amenities: ['wifi', 'breakfast', 'bathtub', 'aircon'],
        images: ['room-living', 'am-spa'],
      },
      {
        name: 'Canopy Suite',
        roomType: 'suite',
        price: 24600,
        maxGuests: 3,
        size: 780,
        beds: '1 king + sofa bed',
        view: 'Gorge & canopy',
        inventory: 12,
        featured: true,
        description: 'Upper level, treetop windows, a private plunge and enough floor space to do your yoga in the room.',
        amenities: ['wifi', 'poolVilla', 'breakfast', 'butler', 'aircon', 'bathtub'],
        images: ['am-suite', 'am-pool', 'room-living'],
      },
    ],
    reviews: [
      { rating: 5, title: 'The footbridge is not a gimmick', body: 'You cross it twice a day and never tire of it. Rooms are simple but the setting is unmatched in Ubud.', name: 'Hannah L.', travelType: 'couple' },
      { rating: 4, title: 'Bring insect repellent', body: 'It is a rainforest, so expect life. Breakfast basket on the terrace at 7am made up for everything.', name: 'Ravi D.', travelType: 'family' },
    ],
  },

  {
    slug: 'seminyak-beach-club',
    name: 'Seminyak Beach Club & Rooms',
    city: 'Bali',
    country: 'Indonesia',
    region: 'Bali',
    neighbourhood: 'Seminyak',
    lat: -8.6905,
    lng: 115.1535,
    timezone: 'Asia/Makassar',
    propertyType: 'boutique',
    starRating: 4,
    featured: false,
    priceFrom: 6400,
    tagline: 'Twenty-two rooms above a beach club. Bed to bar in thirty seconds.',
    description: [
      'An honest, design-led stay rather than a resort: small rooms, excellent beds, and a shared roof with daybeds, a pool, and a DJ on Friday evenings. Batu Belig beach is across the road.',
      'If you want to be walked out of a room with a tray of fruit, this is the wrong booking. If you want to meet people and not oversleep the sunset, it is the right one.',
    ],
    amenities: A(['wifi', 'pool', 'restaurant', 'bar', 'beachAccess', 'aircon', 'laundry', 'parking']),
    highlights: [
      { title: 'Sunset roof', body: 'West-facing daybeds, 17:30 is the hour to hold.', icon: 'Sunset' },
      { title: 'Walk everywhere', body: 'Seminyak\'s best warungs and boutiques within 800m.', icon: 'Footprints' },
    ],
    policies: {
      checkIn: '14:00',
      checkOut: '11:00',
      cancellation: 'Free cancellation until 24 hours before arrival.',
      pets: 'Not permitted.',
      notes: ['Music on the roof runs until 23:00 on Fri–Sat; rooms 1–6 are the quietest.'],
    },
    gallery: ['cov-seminyak', 'am-poolside', 'room-king', 'am-bar'],
    rooms: [
      {
        name: 'Studio Room',
        roomType: 'deluxe',
        price: 6400,
        maxGuests: 2,
        size: 240,
        beds: '1 queen bed',
        view: 'Street & pool',
        inventory: 10,
        description: 'Compact and clever — storage under the bed, a rain shower, blackouts that actually work.',
        amenities: ['wifi', 'aircon', 'poolAccess'],
        images: ['room-king', 'am-poolside'],
      },
      {
        name: 'Roof Suite',
        roomType: 'suite',
        price: 11900,
        maxGuests: 3,
        size: 460,
        beds: '1 king + sofa bed',
        view: 'Ocean',
        inventory: 4,
        featured: true,
        description: 'Private terrace on the roofline with a daybed, so you keep the sunset without the crowd.',
        amenities: ['wifi', 'aircon', 'poolAccess', 'minibar'],
        images: ['am-bar', 'room-king'],
      },
    ],
    reviews: [
      { rating: 4, title: 'Great value, real beds', body: 'Rooms are small but the mattresses and showers are expensive. Perfect if you are out all day.', name: 'Julien M.', travelType: 'solo' },
      { rating: 4, title: 'Friday nights are loud', body: 'On purpose. Ask for a low room if you are an early riser — we did and it worked.', name: 'Kim T.', travelType: 'friends' },
    ],
  },

  {
    slug: 'omotesando-grand',
    name: 'Omotesando Grand',
    city: 'Tokyo',
    country: 'Japan',
    region: 'Kantō',
    neighbourhood: 'Minami-Aoyama',
    lat: 35.6694,
    lng: 139.7109,
    timezone: 'Asia/Tokyo',
    propertyType: 'hotel',
    starRating: 5,
    featured: true,
    priceFrom: 42000,
    tagline: 'A quiet corner of Cat Street with a 12-seat counter that outclasses most restaurants.',
    description: [
      'Sixty-four rooms in a 1989 building quietly rebuilt in 2022, with the original terrazzo lobby kept and everything else replaced with hinoki, washi and low light. The on-site kappo counter seats twelve and books out two weeks ahead.',
      'Ginza station is 6 minutes on foot, Meiji Jingu 9. Rooms are Japanese-standard sized, which is to say compact; the suites are not, and the top-floor ones have a deep soaking tub facing the street trees.',
    ],
    amenities: A(['wifi', 'spa', 'restaurant', 'gym', 'business', 'concierge', 'laundry', 'roomService', 'aircon', 'parking']),
    highlights: [
      { title: '12-seat kappo counter', body: 'Chef-run, omakase at 18:00 and 20:30; guests book at reception.', icon: 'UtensilsCrossed' },
      { title: 'Onsen floor', body: 'Men\'s and women\'s cedar baths on 8, open until 24:00.', icon: 'Flower2' },
      { title: 'Language-first staff', body: 'English, Mandarin and Korean at the desk around the clock.', icon: 'Languages' },
    ],
    policies: {
      checkIn: '15:00',
      checkOut: '11:00',
      cancellation: 'Free cancellation until 14:00 the day before arrival.',
      pets: 'Not permitted.',
      notes: [
        'Rooms are non-smoking throughout; the building has one smoking booth on level 3.',
        'The counter closes Sundays and Mondays.',
      ],
    },
    gallery: ['cov-omotesando', 'am-suite', 'am-spa', 'am-dining', 'am-bar', 'am-desk'],
    rooms: [
      {
        name: 'Washi Room',
        roomType: 'deluxe',
        price: 42000,
        maxGuests: 2,
        size: 344,
        beds: '1 king bed',
        view: 'Street trees',
        inventory: 24,
        description: 'Hinata cedar joinery, a low writing desk, and lighting you can actually read in.',
        amenities: ['wifi', 'aircon', 'bathtub', 'minibar'],
        images: ['am-suite', 'am-desk'],
      },
      {
        name: 'Garden Corner Suite',
        roomType: 'suite',
        price: 78000,
        maxGuests: 3,
        size: 690,
        beds: '1 king + sofa',
        view: 'Inner garden',
        inventory: 8,
        featured: true,
        description: 'Two rooms with a shoji divider, a cedar tub by the window, and the quietest aspect in the building.',
        amenities: ['wifi', 'aircon', 'butler', 'bathtub', 'business', 'roomService'],
        images: ['room-living', 'am-spa', 'am-suite'],
      },
      {
        name: 'Top Floor Residence',
        roomType: 'penthouse',
        price: 168000,
        maxGuests: 4,
        size: 1420,
        beds: '2 kings',
        view: 'City to the bay',
        inventory: 2,
        description: 'Two bedrooms, a tea room, and on a clear February night, Fuji visible from the bath.',
        amenities: ['wifi', 'aircon', 'butler', 'bathtub', 'business', 'roomService', 'laundry'],
        images: ['am-suite', 'room-terrace', 'am-bar'],
      },
    ],
    reviews: [
      { rating: 5, title: 'Book the counter the day you confirm', body: 'Everything was excellent, but the kappo dinner was the reason we would come back. The staff arranged two seatings for us when we got the date wrong.', name: 'Grace N.', travelType: 'couple' },
      { rating: 4, title: 'Small rooms, enormous care', body: 'Standard room is 34m² and honestly fine because the bed and the shower are superb. The suites are where you feel the value.', name: 'Yuto K.', travelType: 'business' },
    ],
  },

  {
    slug: 'bay-glow-tower',
    name: 'Bay Glow Tower',
    city: 'Tokyo',
    country: 'Japan',
    region: 'Kantō',
    neighbourhood: 'Odaiba',
    lat: 35.6274,
    lng: 139.7756,
    timezone: 'Asia/Tokyo',
    propertyType: 'hotel',
    starRating: 4,
    featured: false,
    priceFrom: 19800,
    tagline: 'Rainbow Bridge to the left, skyline to the right, and the bath faces both.',
    description: [
      'A 34-storey tower on the waterfront aimed squarely at two audiences: families using the teamLab and Fuji-TV walks, and photographers who want the bridge from a window. The public onsen on 30 is genuinely good and open to outside guests after 20:00, which is when it is empty.',
      'Rooms start at 32m². Nothing is luxurious, but the views are, and the Yurikamome line is at the door.',
    ],
    amenities: A(['wifi', 'pool', 'gym', 'restaurant', 'spa', 'business', 'laundry', 'aircon', 'kidsClub', 'parking']),
    highlights: [
      { title: 'Bridge-side baths', body: 'Levels 22+ all face the Rainbow Bridge; 30th floor onsen until midnight.', icon: 'Bridge' },
      { title: 'Family floors', body: 'Floors 9–12 have bathrobes in four sizes and a corner bath with a lock.', icon: 'Baby' },
    ],
    policies: {
      checkIn: '15:00',
      checkOut: '11:00',
      cancellation: 'Free cancellation until 24 hours before arrival.',
      pets: 'Not permitted.',
      notes: ['Tattoos are permitted in the onsen after 20:00 under the house policy.'],
    },
    gallery: ['cov-bayglow', 'room-king', 'am-pool', 'am-spa', 'room-terrace'],
    rooms: [
      {
        name: 'Harbour Room',
        roomType: 'deluxe',
        price: 19800,
        maxGuests: 2,
        size: 322,
        beds: '2 twins',
        view: 'Harbour',
        inventory: 30,
        description: 'Water-facing twin with a window bench wide enough to work from.',
        amenities: ['wifi', 'aircon', 'gymAccess'],
        images: ['room-king', 'am-pool'],
      },
      {
        name: 'Skyline Corner',
        roomType: 'suite',
        price: 34500,
        maxGuests: 4,
        size: 620,
        beds: '1 king + 2 twins',
        view: 'Bridge & skyline',
        inventory: 10,
        featured: true,
        description: 'A corner room on 24 or above with the whole bay in two directions and a proper bathtub.',
        amenities: ['wifi', 'aircon', 'bathtub', 'kids', 'roomService'],
        images: ['room-terrace', 'am-spa', 'room-king'],
      },
    ],
    reviews: [
      { rating: 5, title: 'Night views do the work', body: 'We booked for the teamLab and stayed for the onsen at 10pm. Kids loved the family floor robes.', name: 'Meghan O.', travelType: 'family' },
      { rating: 4, title: 'Good, not grand', body: 'Furniture is tired in places but the corner suite view is worth every yen in clear weather.', name: 'Wei Z.', travelType: 'business' },
    ],
  },

  {
    slug: 'le-marais-boutique',
    name: 'Le Marais Boutique',
    city: 'Paris',
    country: 'France',
    region: 'Île-de-France',
    neighbourhood: 'Le Marais',
    lat: 48.8566,
    lng: 2.362,
    timezone: 'Europe/Paris',
    propertyType: 'boutique',
    starRating: 5,
    featured: true,
    priceFrom: 28900,
    tagline: 'A 17th-century hôtel particulier with 19 rooms and a courtyard you will not want to leave.',
    description: [
      'Behind an unmarked door on a rue that ends in a wall, the maison holds its original oak staircase, a walled garden, and a breakfast service that comes out on a tray to wherever you happen to be sitting.',
      'Rooms are individually furnished, most with beams and dormer windows facing the courtyard. There is no gym and no lobby bar; there is a record player in the reading room and a barista at 8am.',
      'Notre-Dame is a 12-minute walk, the Picasso museum 4 minutes, and the best falafel in the arrondissement is on rue des Rosiers if you ask the desk to point.',
    ],
    amenities: A(['wifi', 'spa', 'bar', 'breakfast', 'laundry', 'concierge', 'petFriendly', 'business']),
    highlights: [
      { title: 'Walled courtyard', body: 'Lime trees, 25 seats, and breakfast served there until 11:00 in summer.', icon: 'Trees' },
      { title: '19 rooms only', body: 'No two are alike; six have original 1680s parquet.', icon: 'DoorOpen' },
    ],
    policies: {
      checkIn: '15:00',
      checkOut: '12:00',
      cancellation: 'Free cancellation until 48 hours before arrival.',
      pets: 'Dogs welcome without charge — two beds and a bowl appear.',
      notes: ['Historic building: two rooms are reached by staircase only and there is no lift to the top floor.'],
    },
    gallery: ['cov-lemarais', 'room-living', 'am-bar', 'am-spa', 'am-desk'],
    rooms: [
      {
        name: 'Courtyard Room',
        roomType: 'deluxe',
        price: 28900,
        maxGuests: 2,
        size: 268,
        beds: '1 queen bed',
        view: 'Courtyard',
        inventory: 6,
        description: 'Dormer window over the lime trees, a claw bath, and the quietest night in the arrondissement.',
        amenities: ['wifi', 'breakfast', 'bathtub', 'minibar'],
        images: ['room-living', 'am-bar'],
        featured: true,
      },
      {
        name: 'Garden Suite',
        roomType: 'suite',
        price: 54600,
        maxGuests: 3,
        size: 620,
        beds: '1 king + sofa bed',
        view: 'Garden',
        inventory: 3,
        description: 'Ground floor, opening onto its own paved terrace, with a salon and a writing desk under the beams.',
        amenities: ['wifi', 'butler', 'breakfast', 'bathtub', 'business'],
        images: ['am-suite', 'room-living', 'am-desk'],
      },
    ],
    reviews: [
      { rating: 5, title: 'The courtyard is the whole review', body: 'Tray breakfast under the trees at 9am in June. We barely saw our rooms. Dog-friendly without the usual token bowl.', name: 'Camille R.', travelType: 'couple' },
      { rating: 4, title: 'Beautiful, but mind the stairs', body: 'Top-floor rooms are gorgeous and steep. We swapped to a ground-floor room with no argument, which is worth mentioning because other houses charge for it.', name: 'Edward S.', travelType: 'solo' },
    ],
  },

  {
    slug: 'hotel-trocadero-view',
    name: 'Hôtel Trocadéro View',
    city: 'Paris',
    country: 'France',
    region: 'Île-de-France',
    neighbourhood: 'Trocadéro',
    lat: 48.8617,
    lng: 2.2873,
    timezone: 'Europe/Paris',
    propertyType: 'hotel',
    starRating: 5,
    featured: false,
    priceFrom: 36400,
    tagline: 'Forty-one rooms arranged so that almost none of them miss the tower.',
    description: [
      'A Belle Époque front de mer building, reopened after a five-year restoration with 41 rooms and two suites that have the Eiffel Tower framed like a painting above the mantelpiece. The restaurant on the corner is separately owned and worth eating at twice.',
      'Ask for the left half of the 5th floor for a tower view without facing the full glare of the light show; the shutters are real and they do work.',
    ],
    amenities: A(['wifi', 'restaurant', 'bar', 'gym', 'concierge', 'business', 'roomService', 'spa', 'aircon', 'breakfast']),
    highlights: [
      { title: 'Tower-facing floors', body: '28 of 41 rooms have a direct sightline; the listing states it honestly.', icon: 'Landmark' },
      { title: 'Corner restaurant', body: 'Six tables reserved for guests at 19:30, every night except Monday.', icon: 'UtensilsCrossed' },
    ],
    policies: {
      checkIn: '15:00',
      checkOut: '12:00',
      cancellation: 'Free cancellation until 72 hours before arrival.',
      pets: 'Pets up to 12kg, €25 per night.',
      notes: ['The light show is audible until 23:00 on the front-facing rooms in summer.'],
    },
    gallery: ['cov-trocadero', 'room-terrace', 'am-bar', 'am-suite', 'am-dining'],
    rooms: [
      {
        name: 'Garden Room',
        roomType: 'deluxe',
        price: 36400,
        maxGuests: 2,
        size: 300,
        beds: '1 king bed',
        view: 'Garden & rooftops',
        inventory: 13,
        description: 'Rear aspect, deep windows and a desk that gets the afternoon light. Quietest rooms in the house.',
        amenities: ['wifi', 'aircon', 'roomService', 'minibar'],
        images: ['am-suite', 'am-dining'],
      },
      {
        name: 'Tower Room',
        roomType: 'deluxe',
        price: 62800,
        maxGuests: 2,
        size: 360,
        beds: '1 king bed',
        view: 'Eiffel Tower',
        inventory: 9,
        featured: true,
        description: 'A French window, a chair by it, and the tower from the base of the lattice to the lights.',
        amenities: ['wifi', 'aircon', 'roomService', 'minibar', 'bathtub'],
        images: ['room-terrace', 'am-suite'],
      },
      {
        name: 'Passy Suite',
        roomType: 'suite',
        price: 121000,
        maxGuests: 4,
        size: 1080,
        beds: '1 king + 2 singles',
        view: 'Tower & river',
        inventory: 2,
        description: 'Living room with a piano, terrace facing the river, and a bathroom long enough for the wedding party.',
        amenities: ['wifi', 'aircon', 'butler', 'bathtub', 'roomService', 'business'],
        images: ['room-living', 'room-terrace', 'am-bar'],
      },
    ],
    reviews: [
      { rating: 5, title: 'The Tower Room earns its name', body: 'We took the 6am alarm for once in our lives because the tower at dawn was better than the light show. Shutters block everything.', name: 'Olivia & Sam', travelType: 'couple' },
      { rating: 5, title: 'Restaurant reservation, done for you', body: 'Two nights, two tables at the corner place, both arranged by reception in a minute. Small thing, made the trip.', name: 'Anders P.', travelType: 'solo' },
    ],
  },

  {
    slug: 'villa-adele-santorini',
    name: 'Villa Adèle',
    city: 'Santorini',
    country: 'Greece',
    region: 'Cyclades',
    neighbourhood: 'Imerovigli',
    lat: 36.424,
    lng: 25.4609,
    timezone: 'Europe/Athens',
    propertyType: 'villa',
    starRating: 6,
    featured: true,
    priceFrom: 46800,
    tagline: 'Eleven suites cut into the caldera rock, and a pool that ends at the cliff.',
    description: [
      'Carved into the Skaros rock on the quiet north side of Imerovigli, Villa Adèle is the rare Santorini property where you can hear yourself think. Every suite is cave-vaulted with a private terrace, and the 25-metre pool sits on the shelf above the drop.',
      'Sunset is on your terrace, not in a queue in Oia. Breakfast is served whenever you say between 7 and 11. There are five staff to eleven suites, which is the whole point.',
      'The path down to the cove is 340 steps; a boat collects guests from Ammoudi if you would rather not walk back up in August.',
    ],
    amenities: A(['wifi', 'pool', 'poolVilla', 'spa', 'restaurant', 'breakfast', 'butler', 'airportTransfer', 'concierge', 'yacht', 'roomService', 'aircon']),
    highlights: [
      { title: 'Cliff-edge pool', body: '25m, salt-water, no fence by design, open from 7am.', icon: 'Waves' },
      { title: 'Quiet side of the caldera', body: 'Imerovigli rather than Oia — sunset from your own terrace.', icon: 'Sunset' },
      { title: 'Boat instead of stairs', body: 'Private pickup from Ammoudi bay on request, 15 minutes.', icon: 'Ship' },
    ],
    policies: {
      checkIn: '15:00',
      checkOut: '11:00',
      cancellation: 'Free cancellation until 14 days before arrival.',
      pets: 'Not permitted.',
      notes: [
        'Suites are carved into living rock, so humidity is high in winter; the property closes 1 Nov – 20 Mar.',
        'The pool is unfenced and 1.9m deep throughout — not suitable for toddlers.',
      ],
    },
    gallery: ['cov-adele', 'am-infinity', 'am-suite', 'am-spa', 'room-terrace', 'am-dining', 'am-beach'],
    rooms: [
      {
        name: 'Caldera Cave Suite',
        roomType: 'suite',
        price: 46800,
        maxGuests: 2,
        size: 680,
        beds: '1 king bed',
        view: 'Caldera',
        inventory: 5,
        featured: true,
        description: 'Vaulted ceiling, a terrace with a plunge tub, and the volcano dead centre.',
        amenities: ['wifi', 'aircon', 'butler', 'breakfast', 'plungePool'],
        images: ['am-infinity', 'am-suite'],
      },
      {
        name: 'Two-Bedroom Villa',
        roomType: 'villa',
        price: 98200,
        maxGuests: 5,
        size: 1800,
        beds: '2 kings + single',
        view: 'Caldera & sea',
        inventory: 2,
        description: 'Two suites joined by an outdoor living room and a private pool that sits on the edge of the shelf.',
        amenities: ['wifi', 'poolVilla', 'butler', 'kitchen', 'breakfast', 'aircon'],
        images: ['room-villa', 'am-infinity', 'am-dining'],
      },
    ],
    reviews: [
      { rating: 5, title: 'No queue for sunset, ever', body: 'We drove into Oia once, saw the crowd, and came back to our terrace. That is the entire review honestly.', name: 'Elif & Can', travelType: 'couple' },
      { rating: 5, title: 'Five staff, eleven suites', body: 'Nobody was ever waiting for anything. The boat from Ammoudi saved our knees after a day of walking.', name: 'John R.', travelType: 'friends' },
      { rating: 4, title: 'Mind the pool depth', body: 'Beautiful and honest about being unfenced — our toddlers meant we stayed in the lower terrace instead, which was fine.', name: 'Anneke V.', travelType: 'family' },
    ],
  },

  {
    slug: 'oia-cliff-residences',
    name: 'Oia Cliff Residences',
    city: 'Santorini',
    country: 'Greece',
    region: 'Cyclades',
    neighbourhood: 'Oia',
    lat: 36.461,
    lng: 25.3753,
    timezone: 'Europe/Athens',
    propertyType: 'hotel',
    starRating: 5,
    featured: false,
    priceFrom: 27400,
    tagline: 'White-walled suites stacked down the Oia cliff, five minutes from the castle path.',
    description: [
      'Twenty-four suites in the old captain\'s quarter of Oia, restored with local pumice plaster and lime wash that is repainted every April. The common pool is small and shallow and always busy; the upper terrace is not, and has the better view.',
      'It is in the middle of the sunset crowd, which is either the reason you come or the reason you do not. Book the 18:00 restaurant slot if you want to eat without seeing a phone screen.',
    ],
    amenities: A(['wifi', 'pool', 'restaurant', 'breakfast', 'concierge', 'spa', 'airportTransfer', 'laundry', 'aircon']),
    highlights: [
      { title: 'Castro walk in 5 min', body: 'Start early; the path fills from 17:30 in July.', icon: 'Footprints' },
      { title: 'Upper terrace', body: 'The quiet half of the sunset, ten steps from the rooms on level 3.', icon: 'Sunset' },
    ],
    policies: {
      checkIn: '15:00',
      checkOut: '11:00',
      cancellation: 'Free cancellation until 7 days before arrival.',
      pets: 'Not permitted.',
      notes: ['Access involves 60–90 steps from the lane; luggage is carried by staff, mobility should be discussed first.'],
    },
    gallery: ['cov-village', 'am-poolside', 'am-suite', 'am-bar', 'am-dining'],
    rooms: [
      {
        name: 'Whited-wash Suite',
        roomType: 'suite',
        price: 27400,
        maxGuests: 2,
        size: 420,
        beds: '1 king bed',
        view: 'Village & caldera',
        inventory: 9,
        description: 'Vaulted alcove bed, hand-troweled plaster, and a balcony over the lane.',
        amenities: ['wifi', 'aircon', 'breakfast', 'poolAccess'],
        images: ['am-suite', 'am-poolside'],
      },
      {
        name: 'Sunset Junior Suite',
        roomType: 'suite',
        price: 41200,
        maxGuests: 3,
        size: 640,
        beds: '1 king + sofa bed',
        view: 'Sunset, direct',
        inventory: 6,
        featured: true,
        description: 'West-facing with its own jacuzzi on a terrace deep enough for dinner for four.',
        amenities: ['wifi', 'aircon', 'butler', 'jacuzzi', 'breakfast'],
        images: ['am-bar', 'am-suite', 'room-terrace'],
      },
    ],
    reviews: [
      { rating: 5, title: 'Worth the crowds if you stay upstairs', body: 'Level 3 terrace at 19:40 was empty. Everything below was a festival. Pick your floor deliberately.', name: 'Dana K.', travelType: 'couple' },
      { rating: 4, title: 'Plan around the steps', body: 'Charming and well-run; my parents found the 90 steps hard and the hotel did not offer a room change once we asked twice.', name: 'Michael B.', travelType: 'family' },
    ],
  },

  {
    slug: 'reef-lagoon-retreat',
    name: 'Reef Lagoon Retreat',
    city: 'Maldives',
    country: 'Maldives',
    region: 'North Malé Atoll',
    neighbourhood: 'Private island',
    lat: 4.2805,
    lng: 73.5256,
    timezone: 'Indian/Maldives',
    propertyType: 'resort',
    starRating: 7,
    featured: true,
    priceFrom: 74900,
    tagline: 'Forty villas on one island, half of them over a lagoon you can see the bottom of.',
    description: [
      'A two-seat seaplane from Velana puts you on a sandbank with 40 villas, of which 22 sit on stilts over the shallows and 18 are on the vegetation side with their own gardens. The house reef is walkable from the beach at any tide, which is the single reason guests come back.',
      'Half-board is the sensible plan: there is one main restaurant, one overwater grill, and a wine cave with 900 bottles, and the alternatives involve a boat.',
      'Reef restoration runs on the south tip — staff will take you there at 7am if you ask, and it is not a marketing exercise; you will see the nurseries and the coral counts.',
    ],
    amenities: A(['wifi', 'pool', 'poolVilla', 'spa', 'restaurant', 'gym', 'beachAccess', 'butler', 'yacht', 'concierge', 'kidsClub', 'roomService', 'aircon', 'breakfast']),
    highlights: [
      { title: 'Walkable house reef', body: 'Six minutes from the beach at low tide, no boat needed.', icon: 'Fish' },
      { title: 'Seaplane transfer', body: 'Included in both directions on full board; 20 minutes each way.', icon: 'PlaneTakeoff' },
      { title: 'Coral nursery', body: 'Open 7:00 daily; adopt a frame and it is geo-tagged to your villa.', icon: 'Sprout' },
    ],
    policies: {
      checkIn: '14:00',
      checkOut: '12:00',
      cancellation: 'Free cancellation until 30 days before arrival.',
      pets: 'Not permitted.',
      notes: [
        'Seaplanes operate daylight hours only (06:00–15:30); late arrivals stay one night in Malé at the partner hotel, included.',
        'Green tax of USD 6 per person per night is levied by the government and billed on arrival.',
      ],
    },
    gallery: ['cov-reef', 'room-villa', 'am-infinity', 'am-spa', 'am-dining', 'am-beach', 'room-living'],
    rooms: [
      {
        name: 'Beach Villa',
        roomType: 'villa',
        price: 74900,
        maxGuests: 3,
        size: 1290,
        beds: '1 king + daybed',
        view: 'Lagoon & beach',
        inventory: 12,
        description: 'Garden shower, a 6-metre plunge, and eleven steps of sand before the water.',
        amenities: ['wifi', 'poolVilla', 'butler', 'aircon', 'bathtub'],
        images: ['room-villa', 'am-beach'],
      },
      {
        name: 'Overwater Lagoon Villa',
        roomType: 'villa',
        price: 118400,
        maxGuests: 2,
        size: 1420,
        beds: '1 king bed',
        view: 'Lagoon, floor glass',
        inventory: 16,
        featured: true,
        description: 'Glass panel in the living room floor, a ladder down to the reef, and sunset on the water side.',
        amenities: ['wifi', 'aircon', 'butler', 'overwater', 'snorkelGear'],
        images: ['am-infinity', 'am-suite', 'room-villa'],
      },
      {
        name: 'Two-Bedroom Reef Reserve',
        roomType: 'penthouse',
        price: 264000,
        maxGuests: 7,
        size: 4100,
        beds: '2 kings + 2 twins',
        view: 'Ocean both sides',
        inventory: 2,
        description: 'The island\'s only two-wing overwater residence, with a 14-metre pool and a dedicated chef.',
        amenities: ['wifi', 'poolVilla', 'butler', 'chef', 'gymAccess', 'aircon', 'kids'],
        images: ['am-infinity', 'am-spa', 'am-dining', 'room-villa'],
      },
    ],
    reviews: [
      { rating: 5, title: 'The reef is the differentiator', body: 'Turtles from the villa ladder most mornings. Half board was exactly the right call — one of the two restaurants, twice, then the grill.', name: 'Sophie & Marc', travelType: 'couple' },
      { rating: 5, title: 'Seaplane logistics are real', body: 'Our flight landed at 16:40 and they had the Malé night arranged before we asked. Small thing, huge relief.', name: 'Priyanka J.', travelType: 'family' },
      { rating: 4, title: 'Expensive add-ons, honest pricing', body: 'Green tax and the dive programme are extra and clearly stated. No surprises at checkout, which I cannot say about every atoll.', name: 'Graham T.', travelType: 'solo' },
    ],
  },

  {
    slug: 'sunrise-atoll-lodge',
    name: 'Sunrise Atoll Lodge',
    city: 'Maldives',
    country: 'Maldives',
    region: 'Baa Atoll',
    neighbourhood: 'Dhonakfadhdhoo',
    lat: 5.1033,
    lng: 73.0711,
    timezone: 'Indian/Maldives',
    propertyType: 'glamp',
    starRating: 4,
    featured: false,
    priceFrom: 28600,
    tagline: 'Twelve rooms, one reef, and a UNESCO biosphere a boat ride away.',
    description: [
      'A small lodge on the edge of the Baa biosphere, run by a family from the island next door. Twelve rooms, one restaurant, no minibar, and a house reef with manta cleaning stations that a dive guide will happily take you to at dawn.',
      'It is deliberately un-luxurious: ceiling fans or AC depending on the room, sand floor on the deck, and a manager who knows what time you woke up. If you want a butler, book the atoll next door.',
    ],
    amenities: A(['wifi', 'restaurant', 'beachAccess', 'snorkel', 'airportTransfer', 'laundry', 'spa']),
    highlights: [
      { title: 'Manta point at 6am', body: 'Twenty minutes by dhoni during plankton season (May–November).', icon: 'Fish' },
      { title: 'Biosphere reserve', body: 'Hanifaru Bay access is limited and booked through the lodge.', icon: 'Sprout' },
    ],
    policies: {
      checkIn: '13:00',
      checkOut: '11:00',
      cancellation: 'Free cancellation until 21 days before arrival.',
      pets: 'Not permitted.',
      notes: ['Speedboat transfer is 25 minutes and included on stays of four nights or more.'],
    },
    gallery: ['cov-atoll', 'am-beach', 'room-king', 'am-dining'],
    rooms: [
      {
        name: 'Beach Room',
        roomType: 'garden',
        price: 28600,
        maxGuests: 2,
        size: 430,
        beds: '1 queen bed',
        view: 'Beach',
        inventory: 6,
        description: 'Fan-cooled, open-sided at the back, a hammock between two palms and nothing else on the horizon.',
        amenities: ['wifi', 'beachAccess', 'fan'],
        images: ['am-beach', 'room-king'],
      },
      {
        name: 'AC Water Villa',
        roomType: 'villa',
        price: 43500,
        maxGuests: 3,
        size: 780,
        beds: '1 king + single',
        view: 'Lagoon',
        inventory: 6,
        featured: true,
        description: 'Air-conditioned, on stilts, with a net hammock over the water and a ladder down.',
        amenities: ['wifi', 'aircon', 'overwater', 'snorkelGear'],
        images: ['room-villa', 'am-beach'],
      },
    ],
    reviews: [
      { rating: 5, title: 'Real island, real people', body: 'The family runs it properly. Dawn manta trip was the best hour of my year and cost nothing extra.', name: 'Elias F.', travelType: 'solo' },
      { rating: 4, title: 'Bring your own standards', body: 'No luxury, no complaints — just a beautiful reef and good food. Book the AC villa in the wet season, the fan rooms get sticky.', name: 'Zoe H.', travelType: 'couple' },
    ],
  },
];

export const DEMO_USERS = [
  { name: 'Aarav Mehta', email: 'aarav@me.com', role: 'guest' },
  { name: 'Sofia Reyes', email: 'sofia@reyes.studio', role: 'guest' },
  { name: 'James Whitfield', email: 'james.w@northbank.co', role: 'guest' },
  { name: 'Meera Nair', email: 'meera@lightroom.dev', role: 'guest' },
  { name: 'Tomás Ferreira', email: 'tomas@ferreira.pt', role: 'guest' },
];
