#!/usr/bin/env python3
"""Turns the curated media manifest into client assets:
   - client/src/data/media-manifest.js  (path + alt + LQIP per slot)
   - ATTRIBUTIONS.md                    (CC BY-SA credit list, required by the licence)
"""
import json, os, datetime

ROOT = "/home/user/luxora"
M = json.load(open(os.path.join(ROOT, "scripts/media/manifest.json"))) if os.path.exists(os.path.join(ROOT,"scripts/media/manifest.json")) else json.load(open("/home/user/.probe/media/manifest.json"))

out = ["// GENERATED by scripts/media/build_assets.py — do not edit by hand.",
       "// Every entry is free-licensed photography from Wikimedia Commons with credit in ATTRIBUTIONS.md.",
       "export const MEDIA = {"]
attr = []
for slot in sorted(M):
    r = M[slot]
    out.append(
        f"  {json.dumps(slot)}: {{ src: {json.dumps(r['src'])}, thumb: {json.dumps(r['thumb'])}, "
        f"alt: {json.dumps(r['alt'])}, w: {r['w']}, h: {r['h']}, blur: {json.dumps(r['lqip'][:5240])} }},"
    )
    attr.append((slot, r))

out.append("}\n\n/** Look up an image by slot key, e.g. media('cov-rambagh'). */\nexport function media(slot) {\n  return MEDIA[slot]\n}\n\nexport default MEDIA\n")
os.makedirs(os.path.join(ROOT, "client/src/data"), exist_ok=True)
open(os.path.join(ROOT, "client/src/data/media-manifest.js"), "w").write("\n".join(out))

lines = ["# Image attribution", "",
         "All photography in this demo build is sourced from [Wikimedia Commons](https://commons.wikimedia.org)",
         "under free licences (CC BY / CC BY-SA / public domain). Files are stored locally in",
         "`client/public/img/` after being resized and re-compressed for the web; original caption and",
         "author metadata is preserved below as required by the licences.", "",
         f"_Generated {datetime.date.today().isoformat()} by `scripts/media/build_assets.py`._", "",
         "| Slot | Work | Author | Licence |", "| ---- | ---- | ------ | ------- |"]
for slot, r in attr:
    artist = (r["artist"] or "Unknown").replace("|", "/")
    lines.append(f"| `{slot}` | {r['alt'].replace('|','/')} | [{artist}]({r['commons']}) | {r['license']} |")
lines += ["", "## Swapping to Cloudinary", "",
          "In production the `MEDIA` map is overridden by URLs returned from Cloudinary",
          "(see `POST /api/v1/media/signature` and `server/src/config/cloudinary.js`).",
          "Setting `VITE_IMAGE_CDN` on the client rewrites `/img/...` paths to your cloud, so the same",
          "component code works against either source.", ""]
open(os.path.join(ROOT, "ATTRIBUTIONS.md"), "w").write("\n".join(lines))
print("wrote client/src/data/media-manifest.js (%d entries)" % len(M), "ATTRIBUTIONS.md")
